### ISSUE TITLE
error to lb build !!!

### ISSUE THREAD

**Issue by icelon** [ParrotSec/parrot-build#1]
The following NEW packages will be installed:
  dctrl-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 170 kB of archives.
After this operation, 571 kB of additional disk space will be used.
Get:1 http://eu.archive.parrotsec.org/mirrors/debian/ jessie/main dctrl-tools amd64 2.23 [170 kB]
Fetched 170 kB in 0s (425 kB/s)
                               dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 1 expected program not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)
P: Begin unmounting filesystems...
P: Saving caches...
Reading package lists...
Building dependency tree...
Reading state information...

¿?¿?¿

**Comment by EclipseSpark** [comment]
hi, we need further info about your build environment + a full log that enables us to see where the build failed, because the package that gives you that error is installed in more that one step

**Comment by icelon** [comment]
ok build all (common mistakes, nothing to mourn) last Git ...
Testing of virtualbox  not working :) ...I imagine I will be the driver for x11 and repeatedly trying to restart the desktop
